### ISSUE TITLE
Cocoa API for maximum file size returns incorrect value for FUSE filesystems

### ISSUE THREAD

**Issue by swt2c** [osxfuse/osxfuse#369]
When calling the Cocoa API -[NSURL getResourceValue:forKey:error] with the NSURLVolumeMaximumFileSizeKey, the returned value is incorrect for FUSE filesystems (e.g., SSHFS).  The API returns YES (success) but nil for the value of the maximum file size and nil for error.

Sample code:

```
const char *mount = "/Volumes/Filesystem";  
NSString *path = [NSString stringWithUTF8String:mount];
NSURL *url = [NSURL fileURLWithPath:path];
NSNumber *maxfilesize;
NSError *error;
BOOL ret = [url getResourceValue:&maxfilesize forKey:NSURLVolumeMaximumFileSizeKey error:&error];
NSLog(@"NSURLVolumeMaximumFileSize: %d %@ %@", ret, maxfilesize, error);
```

Output:
2017-04-03 14:47:11.016 blahm[7723:413180] NSURLVolumeMaximumFileSize: 1 (null) (null)

From what I've been able to gather so far, this maximum file size may be queried at filesystem mount time and then cached.

**Comment by bfleischer** [comment]
I'm able to reproduce the issue with osxfuse 3.5.6 and osxfuse 2.8.3 (last osxfuse 2.x release).

The mount process in version 3.5.6 is asynchronous, meaning the FUSE init handshake will most likely happen after `fuse_vfsop_mount()` resturns. FUSE will delay most incoming file system operations until the handshake is complete. This should be completely transparent.

Version 2.8.3 mounts volumes synchronously, meaning the init handshake has already taken place when `fuse_vfsop_mount()` returns. The file system is fully operational at this point.

Since NSURL returns nil for both versions of FUSE when asked for `NSURLVolumeMaximumFileSizeKey` I think the init process can be ruled out.

On a side note, calling -[NSURL removeCachedResourceValueForKey:] just before -[NSURL getResourceValue:forKey:error:] does not make any difference.

I can see that -[NSURL getResourceValue:forKey:error:] triggers a call to `fuse_vfsop_getattr()` which returns `VOL_CAP_FMT_2TB_FILESIZE` as one of the volumes capabilities. I will need to run more tests, but without knowing what NSURL is doing internally with the information returned by FUSE it will be difficult come up with a solution.

**Comment by swt2c** [comment]
Interesting, I hadn't noticed the -[NSURL removedCachedResourceValueForKey:] before.  Indeed, that doesn't seem to help.

I started a thread on the Apple filesystem-dev mailing list.  A developer from Apple responded and provided some code that is similar to what the -[NSURL getResourceValue:forKey:error:] does.  However, the code as posted returns the correct value when called on a FUSE filesystem.  So, I think there is still something we're missing.

Feel free to check out the thread here:
**https://lists.apple.com/archives/filesystem-dev/2017/Mar/msg00009.html**

**Comment by swt2c** [comment]
Any further ideas about this?

**Comment by bfleischer** [comment]
Have you tried mounting the volume with the `-o local` option? It seems `NSURLVolumeMaximumFileSizeKey` is not supported on non-local volumes.

**Comment by swt2c** [comment]
Interesting.  That sure does make `NSURLVolumeMaximumFileSizeKey` return correctly.  I wonder how NFS, AFP, SMB, etc do it, though, as they don't have the `local` option set.

**Comment by bfleischer** [comment]
`-o local` doesn't do anything besides setting the `MNT_LOCAL` flag of the mount point. FUSE does not behave any differently in case of local mounts. `NSURLVolumeMaximumFileSizeKey` working for local mounts means that NSURL (or an underlying layer) is most likely using a different code path for local mounts than it is for non-local mounts. It looks like there is some logic we are not aware of. 

That being said, I think I found the issue. FUSE does not support the `_PC_FILESIZEBITS` pathconf query. According to the algorithm posted on the filesystem-dev mailing list this should not be an issue:

    // if _PC_FILESIZEBITS isn't supported, check for VOL_CAP_FMT_2TB_FILESIZE

However, after adding support for `_PC_FILESIZEBITS` `NSURLVolumeMaximumFileSizeKey` seems to work for non-local mounts.

**Comment by swt2c** [comment]
> -o local doesn't do anything besides setting the MNT_LOCAL flag of the mount point. FUSE does not behave any differently in case of local mounts. NSURLVolumeMaximumFileSizeKey working for local mounts means that NSURL (or an underlying layer) is most likely using a different code path for local mounts than it is for non-local mounts. It looks like there is some logic we are not aware of.

Yeah, I'm not worried about FUSE behaving differently.  I'm worried about Finder behaving differently if it thinks the filesystem is local, like by making even more requests than it already does.

> That being said, I think I found the issue. FUSE does not support the _PC_FILESIZEBITS pathconf query. According to the algorithm posted on the filesystem-dev mailing list this should not be an issue:

> // if _PC_FILESIZEBITS isn't supported, check for VOL_CAP_FMT_2TB_FILESIZE

> However, after adding support for _PC_FILESIZEBITS NSURLVolumeMaximumFileSizeKey seems to work for non-local mounts.

That's great!  I had thought about trying to figure out how to make the pathconf query work, but I couldn't figure out how.  I see now that its in vnops.

Yeah, there must be something missing in the algorithm that was provided such that it behaves differently local/non-local.

**Comment by swt2c** [comment]
> However, after adding support for _PC_FILESIZEBITS NSURLVolumeMaximumFileSizeKey seems to work for non-local mounts.

Indeed, after adding _PC_FILESIZEBITS, sshfs now reports correctly with NSURLVolumeMaximumFileSize.  For some reason, though, my own filesystem still reports NULL.  I'll have to figure out the difference.

**Comment by swt2c** [comment]
Interesting...after adding _PC_FILESIZEBITS:
- hello DOES report correctly with NSURLVolumeMaximumFileSize
- hello_ll DOES NOT report correctly with NSURLVolumeMaximumFileSize

**Comment by swt2c** [comment]
OK, so I figured out the reason some filesystems still don't work after adding _PC_FILESIZEBITS.  The request by coreservicesd is being denied in `fuse_vnop_pathconf()` by `CHECK_BLANKET_DENIAL()` because it is coming from root and the filesystem is initialized.

(The filesystems that have a successful call to `fuse_vnop_pathconf()` are still uninitialized at the time of the call [`!(data->dataflags & FSESS_INITED)`] so that is why they pass the `CHECK_BLANKET_DENIAL()` check.)

I am not sure there is much point in trying to keep root from accessing anything, so I will probably just use allow_root to work around this part of it.  But I wonder if `fuse_vnop_pathconf()` really needs `CHECK_BLANKET_DENIAL()` at all.

**Comment by bfleischer** [comment]
The new 3.5.7 release should fix the `NSURLVolumeMaximumFileSizeKey` issue. Can you confirm this?

**Comment by swt2c** [comment]
Indeed it does, thanks!

Unfortunately, that did not resolve the errors I'm seeing with Finder.  However, I've found another API that seems to be returning the wrong information.  I'll open a new issue about that.

**Comment by bfleischer** [comment]
Thanks! Feel free to open a new issue for the unresolved Finder error.
