### ISSUE TITLE
fuse: unknown option `iconpath=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns'

### ISSUE THREAD

**Issue by ksherlock** [osxfuse/osxfuse#394]
As of 3.6.2, I'm receiving this error. This was not a problem with 3.6.0. No volume icon is specified.

    fuse: unknown option `iconpath=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns'

**Comment by ksherlock** [comment]
Possibly relevant - I'm using the low level fuse interface.

**Comment by ksherlock** [comment]
You can test with the fuse/example/hello_ll.c program:

    $ clang -Wall hello_ll.c `pkg-config fuse --cflags --libs` -o hello_ll
    $ ./hello_ll mnt
    fuse: unknown option `iconpath=/Library/Filesystems/osxfuse.fs/Contents/Resources/Volume.icns'

**Comment by bfleischer** [comment]
Thanks for the bug report. I'll look into it.

**Comment by ThomasWaldmann** [comment]
I am also seeing this error with the borgbackup tests on travis.

**Comment by bfleischer** [comment]
I will release 3.6.3 later today fixing the issue.

**Comment by bfleischer** [comment]
I've just uploaded 3.6.3. Can you confirm that the issue is fixed in the new release?

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/borgbackup/borg/jobs/254366682 i have just restarted that job (which was failing due to this). But guess it will depend on whether your new release already entered brew or not.

**Comment by ThomasWaldmann** [comment]
Hmm, that was still broken. It only says osxfuse-3.6, so not sure if that is 3.6 latest or 3.6.0.

**Comment by bfleischer** [comment]
The bug exists since 3.6.1. 3.6.0 should be fine.

**Comment by misku** [comment]
To check which version is currently loaded, you can use:
```
sudo kextstat | grep fuse
```
After installing new fuse remember to `unload kext` or reboot you Mac.

**Comment by ThomasWaldmann** [comment]
@misku I've no idea whether I could integrate (VM) reboots into travis-ci runs. But as it is always a fresh VM and there was no osxfuse installed before, it should work also without a reboot I guess?

**Comment by misku** [comment]
@ThomasWaldmann Even in your travis log you can see: `You must reboot for the installation of osxfuse to take effect.` 😉  I can see it's installed from brew:
```
brew install Caskroom/cask/osxfuse
```
And it installs:
```
Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.6
```

If your VM is clean (does not have osxfuse installed before this installation) then you're fine. You just have to make sure that proper version is installed (3.6.3). If 3.6 is installed as a dependency of some other software, you can put a line to install 3.6.3 before any fuse mount happens. Then the proper kext version should be loaded (it will overwrite 3.6 installation).

**Comment by ThomasWaldmann** [comment]
I can confirm 3.6.3 fixes the issue. I tried it, unit tests work. Downgraded to 3.6.2, then tests broken again (with the error seen in top post).
