### ISSUE TITLE
Incorrect work of kernel notifications

### ISSUE THREAD

**Issue by Alex-C-Eltima** [osxfuse/osxfuse#436]
Hi,

My app uses OSXFuse with Objective-C framework, how can I manage kernel notifications about file system changes? They are working incorrectly right now.

At the moment, in OSXFuse 3.7.x, the system is being notified even about the first reading of the folder. So, Finder (or other apps assigned to file system changes) starts recurrently reading all subfolders, when I've just opened the root directory on the disk. 

Previous versions of OSXFuse did not have such behaviour.

**Comment by bfleischer** [comment]
Thanks for the bug report. I will look into it.

**Comment by bfleischer** [comment]
The issue should be fixed in commit https://github.com/osxfuse/kext/commit/938b6fc5d8f3a28a48bbd15dfbf6575ec1c989a2.

**Comment by Alex-C-Eltima** [comment]
Hi, the issue seems to still occur in 3.8.0 build, released on May 07, any help is appreciated.

**Comment by bfleischer** [comment]
Can you provide an example project so that I can reproduce the issue? The loopback file system did not generate unexpected notifications in my tests.

**Comment by Alex-C-Eltima** [comment]
Thank you for your reply, we will prepare and provide you with an example shortly.

**Comment by Alex-C-Eltima** [comment]
Sorry for misunderstanding, we have debugged the issue closer and, while preparing the example for you, found that the problem with 3.8.0 was instigated by our own code. Please close the ticket and accept my apologies.

**Comment by Alex-C-Eltima** [comment]
Ok, it seems to be rather specific case for particularly our scenario, but I will try to explain. In older version of OSXFuse (3.6.3) there was no such problem at all, it occured in 3.7.

In 3.7 you’ve added functionality to notify the system about all modifications of the items (files/folders) upon first detection of the item and upon change of its “modification date” parameter. Which resulted into recurrent reading of subfolders by Finder, due to the fact that our code returns current time as "modification date", because of non-existence of actual modification time parameter for the mounted files, and Fuse started crawling all "modified" subfolders.

In 3.8 however, you’ve removed system notification upon file detection, but upon any modification FUSE still sends the notification to the system, which results into similar recurrent reading of all subfolders. 

In attachment you can find and example, and its source code. 
[fuse_test_bin.zip](https://github.com/osxfuse/osxfuse/files/2017263/fuse_test_bin.zip)
[fuse_test_src.zip](https://github.com/osxfuse/osxfuse/files/2017264/fuse_test_src.zip)

From our perspective, the most proper way to avoid such behavior, is allowing us to manually send modification events using “-invalidateItemAtPath:” method , upon actual modification, not automatically, in plain words to choose the notification method between FUSE 3.6 or 3.8.

**Comment by jeremyspiegel** [comment]
This is also still a problem for my filesystem in osxfuse 3.8.2. If I have a folder whose modification date changes frequently, the new system notifications cause Finder/Chrome/etc to issue a readdir on the folder whenever osxfuse notices that the folder's modification date has changed. This causes high CPU usage if the folder has a large number of children. This problem does not happen in osxfuse 3.6.3.

I don't understand how the commit https://github.com/osxfuse/kext/commit/938b6fc5d8f3a28a48bbd15dfbf6575ec1c989a2 could fix the issue, since `FN_NO_AUTO_NOTIFY` is only set if the getattr fails (and my getattr is always succeeding).

**Comment by bfleischer** [comment]
@jeremyspiegel, @kainjow FUSE for macOS 3.9.0 adds a new mount option called `noautonotify`. When this option is present the kernel extension will no longer post file system change notifications automatically. Then it is completely up to you to post notification for remote changes.
