### ISSUE TITLE
Files not opening through Finder in Catalina

### ISSUE THREAD

**Issue by legsak1mbo** [osxfuse/osxfuse#615]
Testing with the latest Catalina beta. We've updated to the latest FUSE and got our code signed and notarised. The drive mounts fine and most operations seem to work as expected. However double-clicking on a file in Finder does not seem to open it. The target application opens as expected but then sits idle in the dock with no windows. However, opening a file using the File > Open dialog from within the application works fine.

Interestingly...
```
$ cd <to a place on the FUSE drive>
$ open "video.mp4"
```
...doesn't work but...
```
$ cd <to a place on the FUSE drive>
$ qlmanage -p "video.mp4"
```
...does launch QuickTime and the video opens as expected.

Note that this behaviour also exists in the Loopback example project pulled and built fresh.

**Comment by laszloagardi** [comment]
Have the same issue here, tested with the HelloFS example project.

**Comment by bfleischer** [comment]
Mounting the volume with the local option seems to work in some cases. I‘m still investigating the issue, but the lack of any error messages make the task difficult.

**Comment by legsak1mbo** [comment]
Ah yes, the local option seems to work here too. Looks like Box are using that option - whose app works in Catalina - but pCloud are not - and their app also seems to work fine.

Also, possibly related, Box seems to be signed an notarised but pCloud does not.

**Comment by bfleischer** [comment]
As far as I can tell the launched application uses the wrong path to open the double-clicked file. I don't know if the wrong file path was passed to the application from Finder (or launchd) or if the file path is altered by AppKit.

It looks like the path of the double-clicked file is treated as a relative path and is appended to the current working directory of the running process. The process then calls getattrlist() on the wrong path and receives an error, since the file does not exist. 

This all happens before [NSApplicationDelegate allocation:openFile:] is called. This means that there is a high probability that all AppKit based apps are affected by this issue.

**Comment by Robert-F** [comment]
While I could reproduce this issue up until Beta 7, I cannot reproduce it in the latest Beta 8 anymore. So it may have been caused by a bug in macOS which has been fixed by Apple.

**Comment by laszloagardi** [comment]
If "direct_io" mount option is specified, then Preview still cannot open the files. Now an error appears that the file may be damaged, when it is not. Other apps seem to open the files correctly through Finder.

Preview logs the following error message to console:
default 10:40:38.388686+0200    Preview com.apple.revisiond [WARNING] This volume is runnning "osxfuse" which is not supported
default 10:40:38.907368+0200    Preview     PVImageContainer initWithURL:file:///Users/<path_to_mount_dir>/Folder/IMG_0058.PNG failed, error = Error Domain=NSCocoaErrorDomain Code=259 "The file “IMG_0058.PNG” could not be opened." UserInfo={NSURL=file:///Users/<path_to_mount_dir>/Folder/IMG_0058.PNG, NSLocalizedDescription=The file “IMG_0058.PNG” could not be opened., NSLocalizedRecoverySuggestion=It may be damaged or use a file format that Preview doesn’t recognise.}

**Comment by bfleischer** [comment]
I can confirm that the issue (files not opening) was caused by a bug in Catalina. Thank you to everyone who looked into the issue and helped tracking it down.

**Comment by laszloagardi** [comment]
@bfleischer do you have any information if the bug is being fixed in Catalina? I'm still experiencing the same issue on Beta 10 (GM).
